import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, ClipboardList, FileText, Database, Layers, Download, LogOut } from 'lucide-react';
import './styles.css';

const STORAGE_KEY = 'cgif-web-mvp-v1';
const POLICY_PACK_ID = 'CMS-LDCT-FFS-DEMO-2026.05';

const sampleCases = [
  { case_id:'FFS-LDCT-001', service:'LDCT screening', claim_service_observed:true, claim_code:'71271', visit_observed:true, risk_support:true, payment_status:'paid', denial:false, ehr_order:false, eligibility:false, sdm_note:false, scheduling:false, auth:'not_observed', care_note:false, access_barrier:false, conflicting:false, source:'synthetic_claims_001' },
  { case_id:'FFS-LDCT-002', service:'LDCT screening', claim_service_observed:false, claim_code:'', visit_observed:true, risk_support:true, payment_status:'no_service_claim', denial:false, ehr_order:false, eligibility:false, sdm_note:false, scheduling:false, auth:'not_observed', care_note:false, access_barrier:false, conflicting:false, source:'synthetic_claims_002' },
  { case_id:'FFS-LDCT-003', service:'LDCT screening', claim_service_observed:true, claim_code:'71271', visit_observed:false, risk_support:false, payment_status:'denied', denial:true, ehr_order:false, eligibility:false, sdm_note:false, scheduling:false, auth:'not_observed', care_note:false, access_barrier:false, conflicting:false, source:'synthetic_claims_003' },
  { case_id:'FFS-LDCT-004', service:'LDCT screening', claim_service_observed:false, claim_code:'', visit_observed:true, risk_support:true, payment_status:'no_service_claim', denial:false, ehr_order:true, eligibility:true, sdm_note:false, scheduling:false, auth:'not_observed', care_note:false, access_barrier:false, conflicting:false, source:'synthetic_hybrid_004' },
  { case_id:'FFS-LDCT-005', service:'LDCT screening', claim_service_observed:false, claim_code:'', visit_observed:true, risk_support:true, payment_status:'no_service_claim', denial:false, ehr_order:true, eligibility:true, sdm_note:true, scheduling:true, auth:'approved', care_note:true, access_barrier:true, access_barrier_type:'transportation barrier documented', conflicting:false, source:'synthetic_hybrid_005' },
  { case_id:'FFS-LDCT-006', service:'LDCT screening', claim_service_observed:true, claim_code:'71271', visit_observed:false, risk_support:false, payment_status:'denied', denial:true, ehr_order:false, eligibility:false, sdm_note:false, scheduling:false, auth:'not_observed', care_note:false, access_barrier:false, conflicting:true, source:'synthetic_claims_006' }
];

const policyPack = {
  policy_pack_id: POLICY_PACK_ID,
  service: 'Low-dose CT lung cancer screening',
  version: 'web-mvp-0.1',
  source_layers: ['Claims', 'EHR / chart', 'Scheduling workflow', 'Payer status', 'Care coordination'],
  guardrails: [
    'Do not infer patient refusal from claims-only service absence.',
    'Do not infer access barrier without documented care coordination evidence.',
    'Do not infer provider failure without order or scheduling evidence.',
    'Do not infer full eligibility without chart evidence.',
    'Do not treat a payment issue as final until coding and documentation are reviewed.'
  ]
};

function readState(){ try { return JSON.parse(localStorage.getItem(STORAGE_KEY)); } catch { return null; } }
function writeState(state){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function asBool(v){ if(typeof v === 'boolean') return v; return ['true','1','yes','observed','available','present'].includes(String(v).toLowerCase()); }
function normalize(c){ return { ...c,
  claim_service_observed: asBool(c.claim_service_observed), visit_observed: asBool(c.visit_observed), risk_support: asBool(c.risk_support), denial: asBool(c.denial), ehr_order: asBool(c.ehr_order), eligibility: asBool(c.eligibility), sdm_note: asBool(c.sdm_note), scheduling: asBool(c.scheduling), care_note: asBool(c.care_note), access_barrier: asBool(c.access_barrier), conflicting: asBool(c.conflicting)
}; }
function coverage(c){ const f=['claim_service_observed','visit_observed','risk_support','ehr_order','eligibility','sdm_note','scheduling','care_note']; return Math.round(f.filter(x=>c[x]).length / f.length * 100); }
function missing(c){ const m=[]; if(!c.ehr_order)m.push('EHR provider order'); if(!c.eligibility)m.push('Clinical eligibility / chart evidence'); if(!c.sdm_note)m.push('Shared decision-making documentation'); if(!c.scheduling)m.push('Scheduling / referral record'); if(!c.auth || c.auth==='not_observed')m.push('Prior authorization / payer status'); if(!c.care_note)m.push('Care coordination / access note'); return m; }
function guardrails(c){ const g=[]; if(!c.claim_service_observed){ g.push('Do not conclude patient refusal.'); g.push('Do not conclude provider failure.'); } if(!c.eligibility)g.push('Do not conclude full clinical eligibility.'); if(!c.scheduling)g.push('Do not conclude scheduling breakdown.'); if(!c.care_note || !c.access_barrier)g.push('Do not conclude access barrier.'); if(c.denial)g.push('Do not finalize payment/coding interpretation without review.'); return [...new Set(g)]; }
function route(raw){ const c=normalize(raw); const pay=String(c.payment_status||'').toLowerCase(); const auth=String(c.auth||'').toLowerCase(); let output,queue,owner,priority,risk,action;
  if(c.conflicting){ output='Conflicting evidence'; queue='Compliance Review'; owner='Compliance reviewer'; priority='High'; risk=92; action='Escalate for manual reconciliation.'; }
  else if(c.denial || pay==='denied'){ output='Coding / payer support issue'; queue='Coding & Revenue Cycle'; owner='Coding analyst'; priority='High'; risk=84; action='Review claim code, support, payer reason, and chart documentation.'; }
  else if(['pending','delayed','denied'].includes(auth)){ output='Prior authorization friction'; queue='Prior Authorization'; owner='Prior auth specialist'; priority='High'; risk=78; action='Resolve payer authorization status.'; }
  else if(c.access_barrier && c.care_note){ output='Access barrier supported'; queue='Care Coordination'; owner='Care coordinator'; priority='Medium'; risk=67; action='Route to patient navigation and document follow-up.'; }
  else if(c.ehr_order && !c.sdm_note){ output='Documentation gap'; queue='Clinical Documentation Review'; owner='Chart reviewer'; priority='High'; risk=74; action='Verify required documentation.'; }
  else if(!c.claim_service_observed){ output='Reason indeterminate'; queue='Chart Review Intake'; owner='Chart review team'; priority='Medium'; risk=56; action='Pull EHR, scheduling, payer, and care coordination evidence before assigning cause.'; }
  else { output='Service observed'; queue='Sampling / No Immediate Exception'; owner='Quality analyst'; priority='Low'; risk=20; action='No urgent exception; sample if audit-readiness is required.'; }
  const known=[c.claim_service_observed?'Service claim observed':'Service claim not observed']; if(c.claim_code)known.push(`Claim code: ${c.claim_code}`); if(c.visit_observed)known.push('Related visit observed'); if(c.risk_support)known.push('Claims-level risk support observed'); if(c.denial)known.push('Denial/payment signal observed'); if(c.ehr_order)known.push('EHR order available'); if(c.access_barrier)known.push(`Access barrier: ${c.access_barrier_type || 'documented'}`);
  return { case:c, case_id:c.case_id, output, queue, owner, priority, risk, coverage:coverage(c), action, known, missing:missing(c), guardrails:guardrails(c) };
}
function tone(p){ return p==='High'?'danger':p==='Medium'?'warn':'success'; }
function download(name, data, type='application/json'){ const blob=new Blob([type==='text/csv'?data:JSON.stringify(data,null,2)],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
function csv(rows){ if(!rows.length)return ''; const cols=Object.keys(rows[0]); return [cols.join(','), ...rows.map(r=>cols.map(c=>JSON.stringify(r[c]??'')).join(','))].join('\n'); }
function Pill({children,toneName='neutral'}){ return <span className={`pill ${toneName}`}>{children}</span>; }

function Login({onLogin}){ const [name,setName]=useState('Demo Reviewer'); const [role,setRole]=useState('Compliance Reviewer'); return <div className="login"><div className="loginCard"><ShieldCheck size={36}/><h1>CGIF Web MVP</h1><p>Evidence review and routing workbench.</p><label>Name</label><input value={name} onChange={e=>setName(e.target.value)}/><label>Role</label><select value={role} onChange={e=>setRole(e.target.value)}><option>Compliance Reviewer</option><option>Chart Reviewer</option><option>Coding Analyst</option><option>Care Coordinator</option><option>Quality Analyst</option></select><button onClick={()=>onLogin({name,role})}>Enter workbench</button><small>Prototype login only. Persistence uses browser localStorage.</small></div></div>; }
function Metric({label,value,detail}){ return <div className="metric"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div><div className="muted">{detail}</div></div>; }

function App(){ const saved=readState(); const [user,setUser]=useState(saved?.user||null); const [cases,setCases]=useState(saved?.cases||sampleCases); const [reviews,setReviews]=useState(saved?.reviews||{}); const [page,setPage]=useState('queue'); const [active,setActive]=useState(saved?.active||'FFS-LDCT-002'); const [q,setQ]=useState(''); const [queue,setQueue]=useState('All'); const [priority,setPriority]=useState('All');
  const persist=(next)=>writeState({user,cases,reviews,active,...next});
  const routed=useMemo(()=>cases.map(route),[cases]); const reviewFor=id=>reviews[id]||{status:'Open',decision:'Pending',assignedTo:'Unassigned',rationale:''};
  const rows=routed.map(x=>({...x, review:reviewFor(x.case_id)})); const queues=['All',...new Set(rows.map(r=>r.queue))];
  const filtered=rows.filter(r=>(`${r.case_id} ${r.output} ${r.queue} ${r.owner}`.toLowerCase().includes(q.toLowerCase()))&&(queue==='All'||r.queue===queue)&&(priority==='All'||r.priority===priority));
  const selected=routed.find(x=>x.case_id===active)||routed[0]; const high=rows.filter(r=>r.priority==='High').length; const open=rows.filter(r=>reviewFor(r.case_id).status!=='Closed').length; const avg=Math.round(rows.reduce((s,r)=>s+r.coverage,0)/Math.max(rows.length,1));
  const saveReview=(id,rev)=>{ const next={...reviews,[id]:{...rev,updatedAt:new Date().toISOString(),updatedBy:user.role}}; setReviews(next); persist({reviews:next}); };
  const receipts=()=>routed.map(x=>({receipt_id:`${x.case_id}-${Date.now()}`,generated_at:new Date().toISOString(),policy_pack_id:POLICY_PACK_ID,case_id:x.case_id,output:x.output,queue:x.queue,owner:x.owner,priority:x.priority,risk:x.risk,evidence_coverage:x.coverage,known_facts:x.known,missing_evidence:x.missing,do_not_conclude:x.guardrails,next_action:x.action,reviewer_status:reviewFor(x.case_id),boundary:'Evidence review and routing only; not final decision system.'}));
  if(!user) return <Login onLogin={u=>{setUser(u); persist({user:u});}}/>;
  return <div className="shell"><aside><div className="brand"><ShieldCheck/><div><b>CGIF</b><span>Web MVP</span></div></div><button className={page==='queue'?'active':''} onClick={()=>setPage('queue')}><ClipboardList/>Work Queue</button><button className={page==='case'?'active':''} onClick={()=>setPage('case')}><FileText/>Case Detail</button><button className={page==='receipts'?'active':''} onClick={()=>setPage('receipts')}><Database/>Audit Receipts</button><button className={page==='policy'?'active':''} onClick={()=>setPage('policy')}><Layers/>Policy Pack</button><div className="sideFooter"><div>{user.name}<span>{user.role}</span></div><button onClick={()=>{setUser(null);persist({user:null});}}><LogOut/>Sign out</button></div></aside><main><header><div><span className="eyebrow">Policy-sensitive review</span><h1>CGIF Web MVP</h1><p>Turn incomplete evidence into work queues, reviewer actions, and audit receipts.</p></div><button onClick={()=>download('cgif_audit_receipts.json',receipts())}><Download size={16}/>Export receipts</button></header><div className="metrics"><Metric label="Cases" value={rows.length} detail="Local prototype database"/><Metric label="High priority" value={high} detail="Needs fast review"/><Metric label="Open work" value={open} detail="Not closed"/><Metric label="Avg evidence" value={`${avg}%`} detail="Coverage"/></div>{page==='queue'&&<section className="panel"><div className="panelHead"><h2>Work Queue</h2><button onClick={()=>download('cgif_work_queue.csv',csv(rows.map(r=>({case_id:r.case_id,output:r.output,queue:r.queue,priority:r.priority,risk:r.risk,status:r.review.status}))), 'text/csv')}>Export CSV</button></div><div className="filters"><input placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)}/><select value={queue} onChange={e=>setQueue(e.target.value)}>{queues.map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option><option>High</option><option>Medium</option><option>Low</option></select></div><table><thead><tr><th>Case</th><th>Output</th><th>Queue</th><th>Priority</th><th>Risk</th><th>Evidence</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.case_id}><td><b>{r.case_id}</b><span>{r.case.service}</span></td><td>{r.output}</td><td>{r.queue}<span>{r.owner}</span></td><td><Pill toneName={tone(r.priority)}>{r.priority}</Pill></td><td>{r.risk}</td><td>{r.coverage}%</td><td><Pill toneName="blue">{r.review.status}</Pill></td><td><button onClick={()=>{setActive(r.case_id);persist({active:r.case_id});setPage('case');}}>Open</button></td></tr>)}</tbody></table></section>}{page==='case'&&selected&&<Case item={selected} review={reviewFor(selected.case_id)} saveReview={saveReview}/>} {page==='receipts'&&<Receipts rows={rows} receipts={receipts} />} {page==='policy'&&<Policy/>}</main></div>;
}
function Case({item,review,saveReview}){ const [decision,setDecision]=useState(review.decision); const [status,setStatus]=useState(review.status); const [assignedTo,setAssignedTo]=useState(review.assignedTo); const [rationale,setRationale]=useState(review.rationale); return <section className="panel"><div className="caseTop"><div><span className="eyebrow">Case detail</span><h2>{item.case_id} · {item.output}</h2><p>{item.queue} · {item.owner}</p></div><div><Pill toneName={tone(item.priority)}>{item.priority}</Pill><Pill>Risk {item.risk}</Pill><Pill>Evidence {item.coverage}%</Pill></div></div><div className="action"><b>Recommended next action:</b> {item.action}</div><div className="grid3"><Card title="What is known" items={item.known}/><Card title="Missing evidence" items={item.missing}/><Card title="Do not conclude" items={item.guardrails}/></div><div className="review"><h3>Reviewer action</h3><div className="formGrid"><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option>Pending</option><option>Agree with CGIF</option><option>Override routing</option><option>Need more evidence</option><option>Escalate</option><option>Close case</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>Open</option><option>In Review</option><option>Waiting for Evidence</option><option>Escalated</option><option>Closed</option></select></label><label>Assigned to<input value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}/></label></div><label>Reviewer rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Add review rationale..."/></label><button onClick={()=>saveReview(item.case_id,{decision,status,assignedTo,rationale})}>Save reviewer action</button></div></section>; }
function Card({title,items}){ return <div className="card"><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div>; }
function Receipts({rows,receipts}){ return <section className="panel"><div className="panelHead"><h2>Audit Receipts</h2><button onClick={()=>download('cgif_audit_receipts.json',receipts())}>Export JSON</button></div><table><thead><tr><th>Case</th><th>Output</th><th>Queue</th><th>Priority</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.case_id}><td><b>{r.case_id}</b></td><td>{r.output}</td><td>{r.queue}</td><td><Pill toneName={tone(r.priority)}>{r.priority}</Pill></td><td>{r.review.status}</td></tr>)}</tbody></table></section>; }
function Policy(){ return <section className="panel"><h2>Policy Pack</h2><div className="grid2"><div className="card"><h3>{policyPack.policy_pack_id}</h3><p>{policyPack.service}</p><p>Version {policyPack.version}</p></div><div className="card"><h3>Source layers</h3><ul>{policyPack.source_layers.map(x=><li key={x}>{x}</li>)}</ul></div><div className="card wide"><h3>Guardrails</h3><ul>{policyPack.guardrails.map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="boundary">GitHub Pages version uses browser localStorage. It is a static prototype, not production infrastructure.</div></section>; }

createRoot(document.getElementById('root')).render(<App />);
